# fly.toml app configuration file generated for 94kca7e1-9dn97vqs-sikbv6a8 on 2024-02-08T20:49:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app           ='94kca7e1-9dn97vqs-sikbv6a8'
primary_region='sin'

[build]

[http_service]
  internal_port       =8080
  force_https         =true
  auto_stop_machines  =true
  auto_start_machines =true
  min_machines_running=0
  processes           =['app']

  [http_service.concurrency]
    type      ="requests"
    soft_limit=80
    hard_limit=100

  [[http_service.checks]]
    grace_period="10s"
    interval    ="30s"
    method      ="GET"
    timeout     ="5s"
    path        ="/resources/healthcheck"


[[vm]]
  cpu_kind ='shared'
  cpus     =1
  memory_mb=1024
